load("//tools/lint:lint.bzl", "add_lint_tests")
load(
    "//tools/skylark:drake_cc.bzl",
    "drake_cc_binary",
    "drake_cc_googletest",
    "drake_cc_library",
)

package(default_visibility = ["//visibility:private"])

exports_files(["run_tiers.py"])

drake_cc_library(
    name = "spatula_slip_lib",
    srcs = ["spatula_slip.cc"],
    hdrs = ["spatula_slip.h"],
    data = ["//:all_models"],
    visibility = ["//visibility:public"],
    deps = [
        "//common:essential",
        "//geometry:proximity_properties",
        "//geometry:scene_graph",
        "//geometry/query_results:contact_surface",
        "//math:geometric_transform",
        "//multibody/math:spatial_algebra",
        "//multibody/parsing",
        "//multibody/plant",
        "//multibody/plant:contact_results",
        "//multibody/tree",
        "//systems/analysis:simulator",
        "//systems/framework:context",
        "//systems/framework:diagram",
        "//systems/framework:diagram_builder",
        "//systems/framework:leaf_system",
        "//systems/framework:vector",
        "//systems/primitives",
        "//tools/voxel_sdf_experiments/common:emit",
        "//tools/voxel_sdf_experiments/common:representation",
        "@fmt",
    ],
)

drake_cc_binary(
    name = "spatula_slip",
    srcs = ["spatula_slip_main.cc"],
    deps = [
        ":spatula_slip_lib",
        "//tools/voxel_sdf_experiments/common:representation",
        "@gflags",
    ],
)

drake_cc_googletest(
    name = "spatula_slip_test",
    srcs = ["test/spatula_slip_test.cc"],
    deps = [":spatula_slip_lib"],
)

add_lint_tests()
